services:
  backend:
    container_name: servlet-crud-backend
    restart: always
    build:
      context: .

  nginx:
    image: nginx:latest
    container_name: servlet-crud-nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend



