services:
  backend:
    container_name: servlet-crud-backend
    restart: always
    build:
      context: .
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: servlet-crud-nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - backend-network

  database:
    image: postgres:16
    container_name: servlet-crud-database
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge